/*

389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
            sort(s.begin(),s.end());
            sort(t.begin(),t.end());
        int i=0,j=0;
        for(;i<s.length() && j<t.length();i++,j++)
        {
            if(s[i]!=t[j])
                return t[j];
        }
        
      return t[j];

    }
};
